### ISSUE TITLE
lesson 5

### ISSUE THREAD

**Issue by sergolius** [vickylucky/vickylucky.github.io#7]
По таблице зачет.
Но нужно доделать вторую часть.

**Comment by sergolius** [comment]
1. http://joxi.ru/J2beJdqcv4W0m6
   пропущена ";" из-за этого не применился шрифт.
2. http://joxi.ru/V2VnG0OCa0DB2v
   Желательно кнопки стилизовать с помощью css, а не вставкой изображения.
3. http://joxi.ru/D2Pj6NLcYd81r3
   a) слишком большой отступ между пунктами меню;
   b) на подсвеченном пункте не должно быть градиента, он должен занимать всю высоту родителя(который с фоном). на скришоте он отступает сверху на 1px;
   c) выровнять по вертикали;
   d) пункт вылез за фон.
4. http://joxi.ru/vAWDVEnHykLQrW
   при изменение высоты меню, форма должна остаться выровненной по центру страницы.
   это происходит по-тому, что вы центровали ее с помощью `position: relative;`, а следовало через `position: absolute;`
5. http://joxi.ru/l2Zv3zkTa8QY2J
   у второй кнопки тип должен быть "submit": `type="submit"`, что бы по клику на нее форма отправлялась.
6. http://joxi.ru/DmBX7KPijNYoAP
   http://joxi.ru/Vm6ykjoCXx8prZ
   http://joxi.ru/82QVWJKiZ1W0Ad
   опечатки в css
7. Постарайтесь избавиться от скролла на странице.
   Но не через: 

```
body {
    overflow: hidden;
}
```

**Comment by sergolius** [comment]
1. http://joxi.ru/82QVWJKiZwzLAd
Если проводить по левому краю меню, оно закроется/исчезнет.
Нужно поправить z-index.

**Comment by vickylucky** [comment]
Переделала. Но, не получилось избавиться от скролла... :(

**Comment by sergolius** [comment]
1. CSS `.facebook-btn` - в этом классе опечатка, не определен `box-shadow:`.
2. \- 2. не сделано.
3. Теперь появился пиксель под подсвеченным пунктом меню.
4. \- 4. не исправлено.
5. http://joxi.ru/EA4Na0ocKx03mb
   Этот кусочек нужно тоже сверстать.

**Comment by vickylucky** [comment]
Исправила

**Comment by sergolius** [comment]
Папки переименовали.
А что изменилось в задании №5?

**Comment by vickylucky** [comment]
Прошу прощение, не верно залила правки. Теперь точно, можно проверить задание №5

**Comment by sergolius** [comment]
1. В меню при наведении на элемент все так же не хватает одного пикселя. Подсветка фона не занимает всю высоту меню.
2. Кнопка "Create my Account" все так же стилизована через фоновую картинку.

**Comment by sergolius** [comment]
Зачет.
